// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbXoxEmQLMsszKc-LKTZ02O_hVJqzPojQ',
    appId: '1:39679609803:web:8fd04e1a3a1a8a69f0444e',
    messagingSenderId: '39679609803',
    projectId: 'yack-a30ae',
    authDomain: 'yack-a30ae.firebaseapp.com',
    databaseURL: 'https://yack-a30ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yack-a30ae.firebasestorage.app',
    measurementId: 'G-C3B70CLKW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI9IFXMvdEXeA40dVBY9bbRhL5Or7VrY0',
    appId: '1:39679609803:android:bb8d3aa26998df48f0444e',
    messagingSenderId: '39679609803',
    projectId: 'yack-a30ae',
    databaseURL: 'https://yack-a30ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yack-a30ae.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbXoxEmQLMsszKc-LKTZ02O_hVJqzPojQ',
    appId: '1:39679609803:web:550bf37d433ae392f0444e',
    messagingSenderId: '39679609803',
    projectId: 'yack-a30ae',
    authDomain: 'yack-a30ae.firebaseapp.com',
    databaseURL: 'https://yack-a30ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yack-a30ae.firebasestorage.app',
    measurementId: 'G-5N9SVGWMBV',
  );
}
